### PR TITLE
Update for freebox mini 4k

### PR DESCRIPTION
**Pull request by ChoiZ**
Unfortunately I have a mini 4k.

### CODE REVIEW

**Review by Pouzor — APPROVED** [review]

**Comment by Pouzor** [comment]
Thanks for the feedback. I'm already working on the new Freebox API https://dev.freebox.fr/sdk/os/login/ (little more complex). 
When it will be available for test, I will ping you in the issue #5 (if you want).

**Comment by Pouzor** [comment]
BTW I didn't recognize you, Francois as @ChoiZ :P

**Comment by ChoiZ** [comment]
Yes tell me when it's available. I'll subscribe to #5 ;-)

**Comment by cyrilst** [comment]
I also subscribed to #5 and I'm ready to test the new version on my Freebox mini when it's available :)

**Comment by cyrilst** [comment]
I had a look at the Freebox APIs, and double-checked: the Freebox Mini 4K player has no API available, and won't be controllable this way. Indeed, Freebox API gives you the API version of your player, and for the 4K player it returns: API not available.

But you can enable ADB on the player:
- Paramètres -> à propos -> click 7 times on Build, then
- Paramètres -> Options de développeur -> Activer débogage USB (this also activates ADB on network, not only via USB)
- And then, you can simply use the native Android TV integration : https://www.home-assistant.io/integrations/androidtv/

**Pull request merged**
